MetaData About the Flight Data Set:
- `Airline`:The name of the airline 
- `Source`: The source from which the service begins 
- `Destination`: The destination where the service ends 
- `Route`: Route the flight took. 
- `Dep_Time`: The time when the journey starts from the source. 
- `Arrival_Time`: Time of arrival at the destination. 
- `Duration`: Total duration of the flight. 
- `Total_Stops`: Total stops between the source and destination. 
- `Additional_Info`: Additional information about the flight 
- `Price`: The price of the ticket ▶▶▶ Target 
- `Month`: Month of journey. 
- `WeekDay`: Day at which journey started. 
- `Day`: Date of the start of journey.

In [89]:
import pandas as pd
import numpy as np

In [90]:
df = pd.read_csv('./Preprocessing1.csv')

In [91]:
df.head(3)

,Airline,Source,Destination,Route,Dep_Time,Arrival_Time,Duration,Total_Stops,Additional_Info,Price,Month,WeekDay,Day
0,Jet Airways,Delhi,Banglore,DEL → BOM → COK,20:00,04:25 10 Jun,26h 35m,1 stop,In-flight meal not included,14924,6,Thursday,6.0
1,Jet Airways,Delhi,Cochin,DEL → BOM → COK,16:00,19:00 10 Jun,27h,1 stop,In-flight meal not included,10577,6,Sunday,9.0
2,Jet Airways,Mumbai,Hyderabad,BOM → HYD,19:35,21:05,1h 30m,non-stop,No info,5678,3,Friday,15.0

In [92]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9450 entries, 0 to 9449
Data columns (total 13 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Airline          9450 non-null   object
 1   Source           9450 non-null   object
 2   Destination      9450 non-null   object
 3   Route            9449 non-null   object
 4   Dep_Time         9450 non-null   object
 5   Arrival_Time     9450 non-null   object
 6   Duration         9450 non-null   object
 7   Total_Stops      9250 non-null   object
 8   Additional_Info  9450 non-null   object
 9   Price            9450 non-null   int64
 10  Month            9450 non-null   int64
 11  WeekDay          9450 non-null   object
 12  Day              9214 non-null   float64
dtypes: float64(1), int64(2), object(10)
memory usage: 959.9+ KB

In [93]:
df.describe()

              Price        Month          Day
count   9450.000000  9450.000000  9214.000000
mean    9027.895556     4.718730    13.517582
std     4466.677471     1.162725     8.459792
min     1759.000000     3.000000     1.000000
25%     5198.000000     3.000000     6.000000
50%     8366.000000     5.000000    12.000000
75%    12373.000000     6.000000    21.000000
max    57209.000000     6.000000    27.000000

In [94]:
# What is the average of the flight ticket price? Write your answer correct to two decimal places.
# 9027.89

In [95]:
# During which month did the highest number of flights occur? Months are represented by numerical codes, with January corresponding to 1, February to 2, and so forth.

## s1 : group the data by month  then count the number of flights in each month

In [96]:
months_gp = df.groupby('Month').count()
months_gp

,Airline,Source,Destination,Route,Dep_Time,Arrival_Time,Duration,Total_Stops,Additional_Info,Price,WeekDay,Day
Month,,,,,,,,,,,,
3,2388,2388,2388,2388,2388,2388,2388,2334,2388,2388,2388,2335
4,926,926,926,926,926,926,926,901,926,926,926,902
5,3092,3092,3092,3091,3092,3092,3092,3029,3092,3092,3092,3004
6,3044,3044,3044,3044,3044,3044,3044,2986,3044,3044,3044,2973

In [105]:
# Is the average price of flight tickets higher on weekends (Saturday and Sunday) or on weekdays (Remaining 5 days)?

# day_gp = df.groupby('WeekDay')['Price'].mean()  wrong we are told to mean for weekdays and weekends separately

df_weekdays = df[df['WeekDay'].isin(["Monday", "Tuesday", "Wednesday", "Thursday", "Friday"])]

df_weekends = df[df['WeekDay'].isin(["Saturday", "Sunday"])]

df_weekdays['Price'].mean(), df_weekends['Price'].mean()

(9015.219666215608, 9058.016077170418)

In [98]:
# 1. Two of the entries in the 'Additional_Info' column are 'No info' and 'No Info'. Replace all occurrences of 'No Info' with 'No info'.  
# 2. How many flights fall under airline 'IndiGo' and have 'No info' as additional information?

## 1.
df['Additional_Info'] = df['Additional_Info'].replace('No Info', 'No info')

## 2.
indigo_no_info = df[(df['Airline'] == 'IndiGo') & (df['Additional_Info'] == 'No info')]
indigo_no_info.shape

(1650, 13)

In [99]:
## 3. #Convert the values of 'Duration' into seconds. Enter the average duration (in seconds) of a flight. Enter your answer correct to two decimal places.
df

,Airline,Source,Destination,Route,Dep_Time,Arrival_Time,Duration,Total_Stops,Additional_Info,Price,Month,WeekDay,Day
0,Jet Airways,Delhi,Banglore,DEL → BOM → COK,20:00,04:25 10 Jun,26h 35m,1 stop,In-flight meal not included,14924,6,Thursday,6.0
1,Jet Airways,Delhi,Cochin,DEL → BOM → COK,16:00,19:00 10 Jun,27h,1 stop,In-flight meal not included,10577,6,Sunday,9.0
2,Jet Airways,Mumbai,Hyderabad,BOM → HYD,19:35,21:05,1h 30m,non-stop,No info,5678,3,Friday,15.0
3,Multiple carriers,Delhi,Banglore,DEL → BOM → COK,18:55,01:30 16 Jun,15h 10m,1 stop,In-flight meal not included,7408,5,Monday,6.0
4,Air India,Delhi,Cochin,DEL → COK,17:10,17:55,8h 20m,non-stop,No info,6724,6,Monday,24.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
9445,Air India,Banglore,Cochin,BLR → MAA → DEL,19:30,19:50,8h 55m,1 stop,In-flight meal not included,5932,6,Wednesday,12.0
9446,IndiGo,Delhi,Cochin,DEL → BOM → COK,17:00,21:00,8h 35m,1 stop,No info,6838,3,Sunday,3.0
9447,Multiple carriers,Delhi,Cochin,DEL → BOM → COK,07:05,19:45,15h 15m,1 stop,No info,12615,3,Saturday,9.0
9448,Jet Airways,Kolkata,Banglore,CCU → BOM → BLR,08:20,19:50,12h 5m,1 stop,No info,10844,5,Saturday,18.0
9449,Air India,Kolkata,Banglore,CCU → GAU → IMF → DEL → BLR,14:30,23:15,8h 45m,3 stops,No info,15145,5,Thursday,9.0

In [100]:
df["duration_seconds"] = pd.to_timedelta(
    df['Duration'].str.replace('h', ' hours').str.replace('m', ' minutes') , 
    errors='coerce'
).dt.total_seconds()

In [101]:
df["duration_seconds"].mean()

38957.93650793651

In [102]:
## How many flights started in the Morning and arrived the destination at Evening?

"""
Apply the following functions to the columns Dep_Time and Arrival_Time:

Transform the values in the 'dep_time' and 'arrival_time' columns to represent the hour component. For instance, if an entry is 10:05 June 13 or 10:05, the corresponding value should be 10. 
Then convert the time into four categories as follows:
5 <= hour < 12 = Morning 
12 <= hour < 17 = Afternoon 
17 <= hour < 20 = Evening 
20 <= hour < 5 = Night


"""
# Departure time
df['Dep_Time'] = pd.to_datetime(
    df['Dep_Time'],
    format='%H:%M',
    errors='coerce'
)

# Arrival time: if the column has mixed formats,
# use format='mixed' with dayfirst=True when appropriate.
df['Arrival_Time'] = pd.to_datetime(
    df['Arrival_Time'],
    format='mixed',
    dayfirst=True,
    errors='coerce'
)

df[(df["Dep_Time"].dt.hour >= 5) & (df["Dep_Time"].dt.hour < 12) & (df["Arrival_Time"].dt.hour >= 17) & (df["Arrival_Time"].dt.hour < 20)].shape

(922, 14)

In [103]:
'''
Encode the values of column 'WeekDay' as follows:
Weekends (Sunday, Saturday) = 1
all remaining five days = 0
What is the most frequent (mode) WeekDay?

'''

def encode_weekday(row):
    if row['WeekDay'] in ['Saturday', 'Sunday']:
        return 1
    else:
        return 0
    

df["encoded_WeekDay"] = df.apply(encode_weekday, axis=1)
df.head()

,Airline,Source,Destination,Route,Dep_Time,Arrival_Time,Duration,Total_Stops,Additional_Info,Price,Month,WeekDay,Day,duration_seconds,encoded_WeekDay
0,Jet Airways,Delhi,Banglore,DEL → BOM → COK,1900-01-01 20:00:00,2026-06-10 04:25:00,26h 35m,1 stop,In-flight meal not included,14924,6,Thursday,6.0,95700.0,0
1,Jet Airways,Delhi,Cochin,DEL → BOM → COK,1900-01-01 16:00:00,2026-06-10 19:00:00,27h,1 stop,In-flight meal not included,10577,6,Sunday,9.0,97200.0,1
2,Jet Airways,Mumbai,Hyderabad,BOM → HYD,1900-01-01 19:35:00,2026-10-11 21:05:00,1h 30m,non-stop,No info,5678,3,Friday,15.0,5400.0,0
3,Multiple carriers,Delhi,Banglore,DEL → BOM → COK,1900-01-01 18:55:00,2026-06-16 01:30:00,15h 10m,1 stop,In-flight meal not included,7408,5,Monday,6.0,54600.0,0
4,Air India,Delhi,Cochin,DEL → COK,1900-01-01 17:10:00,2026-10-11 17:55:00,8h 20m,non-stop,No info,6724,6,Monday,24.0,30000.0,0

In [104]:
df["encoded_WeekDay"].value_counts()

encoded_WeekDay
0    6651
1    2799
Name: count, dtype: int64